### ISSUE TITLE
Getting user "lacks permission to update Scene [xxxxx]"

### ISSUE THREAD

**Issue by ctbritt** [mclemente/fvtt-module-polyglot#207]
**Describe the bug**
Player is getting red banners on login that they don't have permission to update scene and/or setting

**To Reproduce**
1. have polyglot loaded
2. Load canvas as a player
3. See several red warning banners

**Expected behavior**
No warning banners

**Screenshots**
<img width="2560" alt="Screen Shot 2022-01-03 at 4 33 54 PM" src="https://user-images.githubusercontent.com/4516034/147982781-ab77cd0d-f463-4cef-a331-7d1fc9bd2459.png">

 - Game System and version Foundry v9.239, Dnd5e 1.5.6
 - Polyglot Version 1.7.28
 - Are you using Babele? yes

**Additional context**
that's all!

**Comment by mclemente** [comment]
Is that just for one player or all of them? Your player can't access the font files because of your Mac's permission and I have no idea how to fix it.

**Comment by Buzzworth** [comment]
I seem to be having the same bug shown above with any custom fonts I use. Anyone who logs in as a player gets the above errors. If that player logs into a GM account the font loads properly on their PC, but when logging back into their player account the error persists and the font does not load. It seems that only accounts that have permission to access the file browser can load fonts. This is not optimal for a variety of reasons, can this be fixed?

**Comment by mclemente** [comment]
I'm closing this issue due to being related to how Polyglot handled custom fonts before Foundry V10, which has been solved by the new way Foundry handles fonts.
