### ISSUE TITLE
Would it be possible to allow certain characters in custom fonts to be ignored?

### ISSUE THREAD

**Issue by mattimeo84** [mclemente/fvtt-module-polyglot#244]
I have some fonts I have found that only have characters included for letters, but not numbers or punctuation (those are in Times New Roman or similar). I would very much like to use the font but ignore the unstyled numbers.

**Comment by mattimeo84** [comment]
Where would I find the file in Forge to update it? Second question, and if I need to open a second issue, I'd be happy to, would it be possible to add the ability to edit LanguageProvider.js or add a custom LanguageProvider.js style fire that can be uploaded to the game?

**Comment by mclemente** [comment]
I'm not sure how to change files in the Forge. You might find better guidance on the Forge discord.
The only way to do this right now would be making your own module. But I'll try making something similar for Foundry, but it would still be better creating your own module.

**Comment by mattimeo84** [comment]
Ok, thanks! I've been working on modified module and I have a question if you have a moment. For sake of ease, I renamed the fonts so I can group them in photoshop, so I would like to use the updated names in the modified module. How would I reference 'D&D - Thieves Cant.ttf' in the LanguageProvider.js file?

This is what I have: "thieves cant": "200% d&d - thieves cant"

**Comment by mclemente** [comment]
Hello, I've finally got this feature in, hope you enjoy it.
