### ISSUE TITLE
Polyglot seems broken on ProseMirror's journal pages?

### ISSUE THREAD

**Issue by mowngle** [mclemente/fvtt-module-polyglot#268]
I no longer see the Polyglot font choice in the journals.  We used to be able to give handouts in "languages" but that appears to only be an option in chat at the moment.

![image](https://user-images.githubusercontent.com/7859458/195082243-304d5135-b317-4b2f-84f3-84ee20b0a000.png)

I have tried disabling all of the modules except for polyglot and libwrapper and it shows the same font choices.

**Comment by mclemente** [comment]
The new journal editor, ProseMirror, currently isn't module-friendly as the old one. For now, the solution is to change the Journal Editor to TinyMCE.

**Comment by TenguGrib** [comment]
> The new journal editor, ProseMirror, currently isn't module-friendly as the old one. For now, the solution is to change the Journal Editor to TinyMCE.

Would that interfere with Monk's Enhanced Journals do you know?

**Comment by grepheavy** [comment]
TinyMCE doesnt work with V11.  any other options?

**Comment by TenguGrib** [comment]
> TinyMCE doesnt work with V11. any other options?

Use the TinyMCE setting inside Monk's Enchanced Journals, not the TinyMCE module.

**Comment by mclemente** [comment]
I am not sure about @grepheavy's issue. It works fine on a world with only Polyglot running.

Anyway, I've found out a way to get it running on ProseMirror today (based on a PF2e change posted on the FVTT discord).
It has its issues, but it is not a "100% not supported" thing anymore.
