### ISSUE TITLE
[BUG] Polyglot - Language selection only shows other languages to GM. - Non-standard system.

### ISSUE THREAD

**Issue by SuccubusKayla** [mclemente/fvtt-module-polyglot#271]
Players are unable to select languages given to them, the items and languages match in the setting, the characters have the items, but no player is able to change from Common to any other language, while the GM is able to change languages. Even if a player has the language item, when the language is spoken as the GM, the player still does not receive the translated text, as if they do not have the item.

Foundry Version: 10
Build: 288
Simple World-Building 0.7.2

**Comment by mclemente** [comment]
Could you send me a zipped copy of your world?

**Comment by SuccubusKayla** [comment]
[couryss-dangerous-mission.zip](https://github.com/League-of-Foundry-Developers/fvtt-module-polyglot/files/9963254/couryss-dangerous-mission.zip)
Here you go.

**Comment by mclemente** [comment]
Sorry for the delay. There was a typo with the regex for items names.
