### ISSUE TITLE
Language Support for Worlds Without Number

### ISSUE THREAD

**Issue by Cup-of-Coffee** [mclemente/fvtt-module-polyglot#274]
**System Name:**
Worlds Without Number

**System Repository or Foundry VTT address:**
https://github.com/SobranDM/foundryvtt-wwn

The WWN v10 beta5 release: https://github.com/SobranDM/foundryvtt-wwn/releases/tag/v1.0.1-beta5

**Does the system has the languages set up on Foundry?**
The default list of languages is in `wwn/modules/config.js` file, in the `"languages"` variable, but the languages used by the character sheets is stored in the worlds file, through `Data\worlds\[Whatever the Game World is called]\data\settings.db`, under the variable key `"wwn.LanguageList"`.

**Does the system uses languages as items?**
No.

**[Optional] If it isn't straightforward, how do I add a language to a character?**
To add languages to the system if you aren't using the default: As GM.
1. Go to Configure Settings.
2. Go to the Worlds Without Number tab.
3. Locate the Language option and paste in the languages you want to use.

Included by default is the languages from the WWN system stored in the `config.js` file.

To add languages to a sheet: As anyone.
1. Open the character sheet (monsters sheets don't support languages).
2. Go to the Details tab.
3. Locate the Language Column and click the `+` symbol.
4. Select the desired language.

The list of languages available is taken from the `settings.db` file.

**Additional context**
I'm uncertain whether this is common or not, but the default language list in the `config.js` file doesn't change, with only the `wwn.LanguageList` array updating if a game uses different languages than the default setting for WWN.

**Comment by mclemente** [comment]
Thank you for being thorough. That was enough for a functioning provider.

**Comment by Cup-of-Coffee** [comment]
There appears to be a bug with the system. When a GM's message is scrambled OOC, it doesn't get translated for anyone who has the language they're speaking in.

**Comment by Cup-of-Coffee** [comment]
There appears to be a bug with the module. With Scramble OOC Chat Messages, a message in a language sent by the GM won't be understood by players despite knowing the language.

**Comment by mclemente** [comment]
Should be fixed now on v1.8.7.
