### ISSUE TITLE
Polyglot and chat bubbles

### ISSUE THREAD

**Issue by Myriade91** [mclemente/fvtt-module-polyglot#276]
Would there be a way to add later on polyglot to chat bubbles. So far in chat bubbles normal text appears.

**Comment by mclemente** [comment]
Are you testing as a player? As a GM, it'll always show as normal text, but it should show the scrambled test for languages unknown by the players.
![image](https://user-images.githubusercontent.com/5288872/215349297-044b4a23-5beb-4c4c-9364-cf2f9e43c50f.png)

**Comment by Myriade91** [comment]
/facepalmOh dear. Sorry i'm an idiot. I tested it as gm. It works in fact. Forget it. envoyé : 29 janvier 2023 à 19:57de : Matheus Clemente ***@***.***>à : mclemente/fvtt-module-polyglot ***@***.***>cc : Myriade91 ***@***.***>, Author ***@***.***>objet : Re: [mclemente/fvtt-module-polyglot] Polyglot and chat bubbles (Issue #276) Are you testing as a player? As a GM, it'll always show as normal text, but it should show the scrambled test for languages unknown by the players. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by mclemente** [comment]
Don't take it on yourself, it isn't that clear.
