### ISSUE TITLE
Can't add custom fonts directory

### ISSUE THREAD

**Issue by mattimeo84** [mclemente/fvtt-module-polyglot#277]
**Describe the bug**
I no longer have the option to choose a custom font's directory

**To Reproduce**
I created a new world.
I enabled Polyglot and libWrapper.
I went to Polyglot settings.
No option to add custom directory.

**Expected behavior**
Previously, I was able to add custom fonts.

**Screenshots**
https://imgur.com/a/lIT0j3W

 - DnD5e 2.1.2
 - Polyglot Version 1.8.7
 - Are you using Babele? No

**Additional context**
Using Forge to host my VTT

**Comment by mclemente** [comment]
That setting doesn't exist anymore since Foundry V10 was released. You should use Foundry's Additional Fonts setting instead.

**Comment by mattimeo84** [comment]
Ok, will do!
