### ISSUE TITLE
"Add Polyglot's fonts to Core" setting overwrites user-uploaded fonts

### ISSUE THREAD

**Issue by JennyOfWorms** [mclemente/fvtt-module-polyglot#278]
**Describe the bug**
Turning on "Add Polyglot's fonts to Core" removes user-uploaded fonts and prevents uploading new fonts

**To Reproduce**
1. Upload a font in Foundry's Additional Fonts settings
2. Turn on "Add Polyglot's fonts to Core" setting
3. Reload
4. Check Foundry's list of Additional Fonts. The font uploaded in step 1 will be missing.

**Expected behavior**
Polyglot should not remove user-uploaded fonts.

 - FoundryVTT version 10 build 291
 - DND5E version 2.1.4
 - Polyglot Version 1.8.7
 - Are you using Babele? No

**Active Modules**
[
    "5e - Custom Abilities & Skills",
    "About Face",
    "About Time",
    "Active Token Effects",
    "Active-Auras",
    "Advanced Macros",
    "Always HP",
    "Argon - Combat HUD",
    "Art Gallery",
    "Autocomplete Whisper",
    "Automated Animations",
    "Automated Conditions 5e",
    "Baileywiki Maps Premium",
    "Beaver's Crafting Module",
    "Beaver's Potions",
    "Beaver's System Adaption dnd5e",
    "Beaver's System Interface",
    "Better Roofs",
    "Boss Bar",
    "Cautious Gamemaster's Pack",
    "CodeMirror",
    "Combat Booster: Turn Marker, Recent Actions and more",
    "Combat Enhancements",
    "Compendium Folders",
    "Conflux Creatures",
    "Crash's Tracking & Training (5e)",
    "Custom CSS",
    "D&D Beyond Importer",
    "DF Active Lights",
    "DF Architect",
    "DF Quality of Life",
    "DF Template Enhancements",
    "DFreds Convenient Effects",
    "Dice Tooltip - DnD5e",
    "DM AI",
    "DnD5e Drag Ruler Integration",
    "Drag Ruler",
    "Dynamic Active Effects SRD",
    "Dynamic effects using Active Effects",
    "Fast Rolls",
    "Forien's Copy Environment",
    "Initiative Double Click",
    "Inline Chats",
    "Introduce Me",
    "Item Containers",
    "Item Macro",
    "JB2A - Patreon Complete Collection",
    "Lasers and Lightbeams",
    "Less Fog",
    "Let Me Roll That For You!",
    "Let's Trade 5e",
    "Levels",
    "lib - Color Settings",
    "libWrapper",
    "Magic Items",
    "Mass Edit",
    "Melvin's Mechanical Masterworks",
    "Merge Walls",
    "Midi QOL",
    "Midi SRD",
    "Module Profiles",
    "Monk's Active Tile Triggers",
    "Monk's Enhanced Journal",
    "Monk's Wall Enhancement",
    "Moulinette Core",
    "Moulinette Game Icons (module)",
    "Moulinette Image Search (module)",
    "Moulinette Scenes (module)",
    "Moulinette Sounds & SoundPad (module)",
    "Moulinette Tiles (module)",
    "Multi Token Status",
    "NameForge",
    "Narrator Tools",
    "Not Your Turn!",
    "Polyglot",
    "Precise Drawing Tools",
    "Pushable tokens",
    "Quick Module Enable",
    "Retroactive Advantage DnD5e",
    "Scene Backup Tool",
    "Sequencer",
    "Settings Extender",
    "Simple Calendar",
    "SmallTime",
    "socketlib",
    "Splatter",
    "Tagger",
    "Times Up",
    "Token Action HUD Core",
    "Token Action HUD D&D 5e",
    "Token Ease",
    "Token Magic FX",
    "Torch",
    "Wall Height",
    "Wild Magic Surge 5e"
]

**Comment by mclemente** [comment]
Sorry for your troubles and thanks for the report, this issue should be fixed now!
