### ISSUE TITLE
[Reopen #279] Sharing compendium entry in chat is broken when a language other than common is used

### ISSUE THREAD

**Issue by uninvitedguest** [mclemente/fvtt-module-polyglot#280]
Issue #279 still persists on Polyglot 1.8.9

![image](https://user-images.githubusercontent.com/24210277/218497452-5f1b6b8c-e80e-4840-9131-ecd7d156367a.png)

![image](https://user-images.githubusercontent.com/24210277/218497500-55dd5119-610e-4f81-a444-f770b4ac567e.png)

**Comment by mclemente** [comment]
Repost.
