### ISSUE TITLE
Missing languages in Shadowrun 5e

### ISSUE THREAD

**Issue by 95Gman** [mclemente/fvtt-module-polyglot#284]
The Polygot module has a list of languages but their text versions are mostly missing.
Is this something to fix on my end?
![image](https://user-images.githubusercontent.com/74572009/227390046-964b4c43-806d-47d2-9908-174162c1beee.png)

**Comment by mclemente** [comment]
I don't remember if the "Olde English" font set was already in when I first made the Shadowrun language provider, so I must have used the default font that was used for other systems.

You can fix this by changing the `Add Fonts to Module Settings` to "Polyglot Fonts" or "All" and set it to Olde English. Future releases of this module will use that font instead.
