### ISSUE TITLE
"/me" doesn't work great with this module

### ISSUE THREAD

**Issue by LtDerek** [mclemente/fvtt-module-polyglot#287]
Usually "/me" is used to describe a character performing a physical action, that is independent of the language it speaks. Anyone can look at a creature that  "/me picks up it's weapon and points it toward you" and interpret some meaning.

This can become a problem with polygot enabled. Mainly in situations where a creature does not have a shared language with the PCs (e.g. anything that doesn't speak common).

In these situations the emote is scrambled into whatever language it is force to select and it's not possible to use the "/me" common to describe it's behaviour to the players. It simply treats it as indecipherable speech. 

This is especially frustrating because these times when the language barrier exists are an ideal time to use physical actions and emotes in order to communicate. 

I would suggest adding an optional feature to disable the polygot function when "/me" is being used.

**Comment by mclemente** [comment]
I can't reproduce this behavior, Polyglot only interacts with IC, OOC and Whisper messages, /me messages are created without any languages.

Are you using any module that changes your messages' behavior? I know Cautious Gamemaster's Pack module does, but that one specifically doesn't change /me messages.

If your last message was a /me message, open the Console (F12) and type `Array.from(game.messages.values()).pop().type`. Is the result `3`?

**Comment by LtDerek** [comment]
I can't reproduce the behaviour either anymore. I must've disabled the conflicting module without realising.
