### ISSUE TITLE
Everyone can read any language 

### ISSUE THREAD

**Issue by MustangDJ** [mclemente/fvtt-module-polyglot#291]
**Describe the bug**

Whenever a character or NPC speaks in a language despite no one in a party knowing that language it is still translated for them. For example, I tried speaking in Grippli (using Pathfinder 2e) despite no character having that language on their sheet it was still translated. 

**To Reproduce**
1. Add "Test" to Custom Languages '...'
2. Add "Test" to a character '....'
3. Send a message '....'
Make a message in any language 
**Expected behavior**
anyone can read any language 
**Screenshots**
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/134565747/462de34f-38c6-492c-ac05-73a6431d4fae)

 - Game System and version [e.g. dnd5e 1.3.6]
 - Polyglot Version 1.9
 - Are you using Babele? [No]
- Pathfinder 2e Version 4.12.2
**Additional context**
This occurred after updating to the most recent patch I am still on the last stable version of Foundry V10 stable patch 6 build 291

**Comment by mclemente** [comment]
Should be fixed now, sorry for your troubles.
