### ISSUE TITLE
Language Drop Down Not working for Players

### ISSUE THREAD

**Issue by XXDarrienX** [mclemente/fvtt-module-polyglot#293]
**Describe the bug**
As a DM I can see all languages in the drop down, when I logged with a test player, there are no other languages other than default Common for D&D5E, the player with ownership of the actor has access to 3 languages, Common Druidic and Gnomish both of which are not selectable in the dropdown at all.

**To Reproduce**
1. Load up a world using D&D5E with the speak as and polyglot and any dependencies.
2. Import a generic starting hero from the 5E Compendium, give ownership to a player
3. Player logs in goes to chat and sees only Common
4. Switch to the DM screen and the dropdown shows all languages.
5. Tried creating a new actor incase it was just bugged to no avail.
6. I tried reloading the entire application and that did not work

**Expected behavior**
The language dropdown should simply show all the languages that character knows,

**Screenshots**

 - Game System and version D&D5E 2.2.1
 - Polyglot Version 1.9.1
 - Are you using Babele? No

**Comment by XXDarrienX** [comment]
![LanguageDropdown](https://github.com/mclemente/fvtt-module-polyglot/assets/28017703/5c41d69f-8662-43e4-bdee-1a86f52f7beb)

**Comment by mclemente** [comment]
Was the player assigned to the character? As in, does their name shows up like this in the players list?
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/5288872/b6175668-8259-4dce-a4fc-5438a922d127)

**Comment by XXDarrienX** [comment]
Nope, and I just realized when I did assign a character its working as normal, I had thought assigning overship was enough my mistake.

**Comment by mclemente** [comment]
It works, but only if the owned character is on a scene, and that can conflict with other owned characters since it will behave just like when a GM selects a token.
