### ISSUE TITLE
Langauge selection has no effect if there's no token on a scene.

### ISSUE THREAD

**Issue by kristianserrano** [mclemente/fvtt-module-polyglot#297]
**Describe the bug**
On a scene without any tokens, language selection in the chat has no effect if a player selects a language and posts a message.

**To Reproduce**
1. Create a Scene _without_ Tokens
2. Login as a Player with an Actor assigned
3. Send a Chat Message in a selected language
4. A regular Chat Message is posted.

**Expected behavior**
I would expect a Chat Message in the selected language to post. Note that the languages in the list are the languages of the assigned Actor

**Screenshots**
![Screenshot 2023-07-06 at 12 06 09 AM](https://github.com/mclemente/fvtt-module-polyglot/assets/1796189/a1aead0c-1918-4f75-b737-f9deacf5948c)

 - System: Savage Worlds Adventure Edition; Version: 2.4.2
 - Polyglot Version: 1.9.4
 - Are you using Babele? No

**Comment by mclemente** [comment]
If there's no owned tokens in a scene, messages are sent as Out of Character, e.g. you could use `/ic Test` and it would show up in the selected language. By default only the GM can speak in a language while OOC, you can change that in Settings > General Settings > Chat > Scramble OOC Chat Messages > All.

**Comment by kristianserrano** [comment]
Ah, OK! Thanks for the pointer. :)
