### ISSUE TITLE
Players cannot edit and save in Journal Entry with Polygot enabled.

### ISSUE THREAD

**Issue by Airwrecker** [mclemente/fvtt-module-polyglot#298]
I have an odd issue where I had created under the Journal tab a "Party Loot" journal entry that I gave the players ownership permission to edit, however, soon before v11 released they couldn't edit it. I turned off the modules one by one to see if one of them was causing the issue and it looks like Polygot was the culprit (disabling Polygot allows the players to edit and save). As GM, I could still edit and save the journal entry though.

**Comment by mclemente** [comment]
Any errors on the console? What system are you on?

**Comment by Airwrecker** [comment]
Foundry v11 stable build 306 (linux)

It looks like it's not necessarily a Polyglot bug but either Monk's Enhanced Journal mod issue or a conflict between that and Polyglot.
1. Turning off one or the other will allow the players to modify and save a journal entry.
2. If both mods are activated, the players can't modify and save a journal entry.
3. Disabling Polyglot and enabling Monk's Enhanced Journal allows the players to modify and save a journal entry.
4. Disabling Monk's Enhanced Journal and enabling Polyglot allows the players to modify and save a journal entry.

```
Uncaught TypeError: polyglot.known_language is undefined
[Detected 1 package: monks-enhanced journal]
  activateEditor http://xxx.xxx.xxx.xxx/modules/monks-enhanced-journal/sheets/EnhancedJournalSheet.js:406
  activateEditor http://xxx.xxx.xxx.xxx/scripts/foundry.js:6761
```

**Comment by mclemente** [comment]
I still have no idea how to reproduce this issue, you should've followed the instructions on the issue when you created this bug report, only now I know you're using MEJ, for example.
Describe how you created that journal entry, a normal Text sheet isn't doing it for me, same for MEJ's Loot sheet.

**Comment by Airwrecker** [comment]
My apologies.

Foundry v11 stable build 306 (Linux)
Polyglot 1.9.4
Monk's Enhanced Journal 11.03

As GM, created a folder called "Party Journal" with three journal entries ("Journal Entry" type) called Loot, Notes, and Objectives (all three have the Owner Configuration set to give "Owner" status "All Players" and individually change each players' status to "Owner"). 

The issue arises on the player client side where they can click on one of the three journal entries (Loot, Notes, or Objectives) and the pages opens, however, when they click on the edit icon (pen with square) nothing happens. As GM, I have no issue editing and saving it.

It appears if journal entry type was "Text" the players can edit and save it on their end.

Again, the issue appears to only happen if both Monk's Enhanced Journal and Polyglot are activated. Disabling one of the two modules will "fix" the editing/saving issue that the players encounter.

I checked on Monk's github page and the issue was also reported back about three weeks ago, affecting Foundry v10 build 303
https://github.com/ironmonk88/monks-enhanced-journal/issues/600
