### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by Imper1um** [mclemente/fvtt-module-polyglot#302]
**Describe the bug**
When you make a change to the Language, those settings do not save to the Server.

**To Reproduce**
1. Go to Configure Settings.
2. Go to Polyglot
3. Click on Language Settings
4. Make any change to Languages (Font, Random). Click Save Changes.
5. In Configure Settings, click Save Settings.
6. Try speaking in the specified language that you made the modification.
7. On your local machine, the language is set properly, but on other users' screens, it will be the original defaults.
8. Reload the webpage on the Local Machine.
9. Go to Configure Settings
10. Go to Polyglot
11. Click on Language Settings.
12. Notice that changes have reverted to default.

**Expected behavior**
Changes to languages propagate to the server.

**Versions**
 - Foundry: v11.305
 - Game System: Starfinder 0.24.2
 - Polyglot: 2.0.1
 - Settings Extender 1.2.2
 - Babele: No

**Comment by mclemente** [comment]
I've fixed it now.

Only thing that isn't "fixed" is the server propagation, because I don't think GMs change their settings mid-session that often, and the best way to propagate would require refreshing and that would be annoying when setting the languages.
