### ISSUE TITLE
Request for New Setting: Read Languages of all Owned Actors/Permission Minimum

### ISSUE THREAD

**Issue by Imper1um** [mclemente/fvtt-module-polyglot#304]
**Is your feature request related to a problem? Please describe.**
At the moment, Polyglot scans the current active scene for tokens and checks for languages on those owned tokens by the Foundry User to determine if they should be able to understand the language, and display the unscrambled text accordingly. However, there are some scenarios in which this would be incorrect:
1. You are an observer of a game in which you are broadcasting to others (like Twitch).
2. You are on a map in which its just a map and does not include the tokens of the player.

**Describe the solution you'd like**
I propose two settings:
1. Permission minimum: The minimum setting a Foundry user must have on a single token/actor that would allow them to utilize the languages of the token/actor (Owner [Default], Observer, Limited).
2. Scan Tokens/Actors: If set to Token, Polyglot will scan the current scene for Tokens and those tokens that meet the Permission Minimum will be used to determine if the Foundry user has permission to view the unscrambled text. If set to Actor, Polyglot will scan all of the actors instead of Tokens on the current scene that meet the permission minimum requirement, and use those languages.

**Describe alternatives you've considered**
In order to make sure that my broadcast observer sees the untranslated text, I have had to give ownership of an "Observer" token that I had to drag onto every Scene. I also need to drag all of the PC's tokens onto every scene when I'm going to be speaking in another language.

**Comment by mclemente** [comment]
1. Couldn't you just assign a character to the observer user (which won't need a token) or give it GM permission?
2. Are the players meant to be able to read the messages in this scenario? Because they can if they have a character assigned to them.

**Comment by mclemente** [comment]
Closing as wontfix.

Players don't need tokens placed on the canvas to be able to read messages if configured properly. Refer to the [wiki](https://github.com/mclemente/fvtt-module-polyglot/wiki#understanding-core-behavior).
