### ISSUE TITLE
Enable/Disable Polyglot for /me, /ooc, /desc

### ISSUE THREAD

**Issue by Imper1um** [mclemente/fvtt-module-polyglot#305]
At the moment, by default, Polyglot has the following settings:
 /me = Disabled
 /ooc = Enabled
 /desc = Enabled
What I think would be a good setting is to select if Polyglot should run for /me, /ooc, or /desc by selecting if it should be enabled or disabled for these types of communication. It would allow users to select when they expect Polyglot to run on their own settings.

**Describe alternatives you've considered**
I avoid /me when I need translation, and I use languages all of the on-screen players know to make sure Polyglot does not do translations.

**Comment by mclemente** [comment]
/me is meant to be used as an emote message, like "[Character Name] does thing", it isn't meant for characters to speak.

/ooc can be toggled by the GM for all users, under the General Settings' Chat tab. It is disabled by default for players.

/desc isn't a Core function, it's from the Narrator Tools. Change the `Narrator's message type` setting back to "Other".

**Comment by Ghostdesu** [comment]
What about /desc from [Cautious Gamemaster Pack](https://github.com/cs96and/FoundryVTT-CGMP)? It doesn't have an equivalent setting, would this be something that would have to be resolved on the other module's side?

**Comment by mclemente** [comment]
I'll add a check for CGMP's flag. Expect it on the next version (2.3.2+).
Also, after my last reply I introduced a checkbox to disable the language being applied to the message, so you can use that in the meantime.
