### ISSUE TITLE
Creating a custom LanguageProvider results in error

### ISSUE THREAD

**Issue by Re4XN** [mclemente/fvtt-module-polyglot#311]
**Describe the bug**
The documentation for creating a custom `LanguageProvider`, if followed, results in the following error: `Receiver must be an instance of class PolyglotAPI`.

**To Reproduce**
Follow steps on [documentation page](https://clemente.gitbook.io/polyglot/api/creating-a-language-provider). Replace last line with `game.polyglot.registerSystem(MyLanguageProvider).`

**Expected behavior**
No errors. Correct functioning of the module.

**Additional Context**
Locally, I managed to fix this by replacing `this.#register` with `this.api.#register` in `api.js`, line 115 (`registerSystem` method).

**Comment by mclemente** [comment]
That documentation page has been deprecated over for [Github's Wiki](https://github.com/mclemente/fvtt-module-polyglot/wiki/API).
I've lost access to that Gitbook, so I can't edit to point to the Wiki or even take it down currently. I'm sorry for the confusion.

**Comment by mclemente** [comment]
Closing this as resolved.

If you have any other questions, feel free to open a [discussion](https://github.com/mclemente/fvtt-module-polyglot/discussions).
