### ISSUE TITLE
Polyglot appears to cause issues with player journals

### ISSUE THREAD

**Issue by MissZerglot** [mclemente/fvtt-module-polyglot#313]
**Describe the bug**
Although I am able to edit any journal, my players have stopped being able to edit journals they have full ownership over. When they open any journal sheet they own to edit it, all options for interacting with the sheet disappear. 

Without polyglot: 
https://i.imgur.com/Hkzb64p.png

With polyglot:
https://i.imgur.com/rHWZeef.png 

The error being thrown: 
https://media.discordapp.net/attachments/722566083499786352/1145702410875052063/image.png?width=664&height=559

**To Reproduce**
I have "Replace all system languages" ticked and filled in a list of custom languages separated by commas. This worked fine until a few weeks ago, when the aforementioned problems began to crop up. I turned polyglot off at the time and left it at that, but I've returned to try and resolve the issue. 

I have the latest version of D&D 5e (2.3.1), Foundry v11 build 208 and 2.1.3 of polyglot 

**Additional context**
I have asked for help in the WFRP4e channel on discord, as through a search I realised that there was at least one other person suffering from the same issue as I was. Fortunately for them, they managed to solve the issue. Unfortunately for me, that solution doesn't appear to work for me. Developer Forien recommended me to open an issue, as the most straight-forward solution appears to be to create a new language provider, but that isn't what the module communicates.

**Comment by mclemente** [comment]
The player has a Special Language set up that isn't defined in the Custom Languages.

I will add a fix so it doesn't break journals, but, for now, a language that isn't defined won't show up on the journal's list.

**Comment by MissZerglot** [comment]
Thank you so much! I suppose it is a little unfortunate. Sometimes my players get special languages for specific creatures as a reward, which has led to them having a few unique languages that aren't set up properly. I appreciate you looking into this!
