### ISSUE TITLE
Polyglot doesn't work with WFRP4e 7.0.0

### ISSUE THREAD

**Issue by Forien** [mclemente/fvtt-module-polyglot#314]
**Describe the bug**
[WFRP4e 7.0.0](https://github.com/moo-man/WFRP4e-FoundryVTT/releases/tag/7.0.0) migrated it's compendia, which broke the Polyglot.
What was `wfrp4e-core.skills` is now `wfrp4e-core.items` as described in moo-man/WFRP4e-FoundryVTT#1729

```js
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getIndex')
    at wfrp4eLanguageProvider.getLanguages (LanguageProvider.js:3504:43)
    at setupSteps (LanguageProvider.js:282:15)
    at wfrp4eLanguageProvider.setup (LanguageProvider.js:313:10)
    at Object.fn (polyglot.js:32:39)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.setupGame (foundry.js:8636:11)
    at async Game._initializeGameView (foundry.js:9912:5)
```

**To Reproduce**
1. Launch the world with WFRP4e 7.0.0, WFRP4e Core 4.0.0 and Polyglot

**Expected behavior**
Polyglot works

**Screenshots**
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/11304207/178bdbe7-c8bc-48d9-adab-710dc5233195)
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/11304207/97ad3924-9ec6-4e40-8ba4-380c7310cc39)

 - Game System and version [wfrp4e 7.0.0 & wfrp4e-core 4.0.0]
 - Polyglot Version [2.1.4]
 - Are you using Babele? [No]

**Additional context**
Separate bug - Polyglot breaks Journals if an Actor has `Language (Battle)`

**Comment by mclemente** [comment]
Fixed on 2.1.5.

As for the other bug, it should've been fixed on #313 earlier today.
