### ISSUE TITLE
Custom language settings do not save correctly (D&D 5e 2.3.1, Foundry v11)

### ISSUE THREAD

**Issue by Janner3D** [mclemente/fvtt-module-polyglot#316]
**Describe the bug**
Language Settings do not show up correctly.

**To Reproduce**
1. Open up Language Settings on Polyglot
**Expected behavior**
The languages should be appearing in the 'languages' column.

**Screenshots**
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/35965176/23121945-6c99-4710-bc70-26446e50b26a)

 - D&D 5e 2.3.1, Foundry v11
 - Polyglot Version 2.1.6
 - Are you using Babele? No

**Comment by mclemente** [comment]
Scroll to the bottom of the Language Settings, click on "Reset Defaults" and it should fix this.

**Comment by Janner3D** [comment]
So that seemed to work initially, but now it's not saving my fonts for the various custom languages I have after reloading foundry.
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/35965176/6726e8dd-7453-4cfb-9878-79ed58e0866f)
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/35965176/116e5fbe-c6d7-4ea7-83d1-7c38dfece882)

I've imported custom fonts made in base foundry.
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/35965176/11542f34-ca81-467f-9fc5-d50e89619109)
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/35965176/e8b3cf1b-3143-4026-9259-ad2a3324ab95)


Setting up languages and hitting save:
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/35965176/b4416e38-0c80-4e4c-8506-77717a93e86d)


After reloading, the fonts are jumbled about and still don't show up in chat:
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/35965176/3bb0dcb0-74b6-421f-931d-8856f773655a)
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/35965176/d8e77230-98a6-48b6-a567-ec99e6dd6286)

I've tried reloading, I've tried restarting the ForgeVTT server I use, nothing seems to work.

**Comment by AdamJDyer** [comment]
I am also experiencing this defect in the same manner.

**Comment by mclemente** [comment]
Thanks for the detailed info. Version 2.1.7 should have fixed this issue for Custom Languages. Try it out and let me know if anything is still wrong.

**Comment by Janner3D** [comment]
I still seem to be getting similar issues. Though there is one thing I've noticed here.
Before reloading:
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/35965176/ba241326-c46b-4b1c-afa8-a3a73f34dd2f)

After Reloading:
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/35965176/c57f8883-c854-4c50-bc8e-10935d122a87)


I'm noticing that it almost seems like certain blocks of fonts are being "shifted up" a couple of notches. They're in sync with Aquan, Auran, and Blacktongue, but it's like it's missed Deep-speech in the fonts, and carries on with an offset of 1. Demonic, Djoran, Draconic, etc, right up until it gets to Under-tongue, which is once again missing from the fonts.

Here's what I have for my custom fonts:
`Aquan,Auran,Black-tongue,Deep-speech,Demonic,Djoran,Draconic,Druidic,Dwarven,Giant,Goblin,Halfling,Ignan,Infernal,Nidean,Nioban,Orcish,Panji,Rat-tongue,Serpentongue,Sylvan,Tahosian,Terran,Thieves-Cant,Trade-tongue,Under-tongue,Vaskarran`
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/35965176/3fb06c21-e3ac-4a95-a553-130fb48a60c5)

Trade-tongue has been set as my default language.
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/35965176/ea7ba587-e2aa-4b90-80d0-a3f6fe0463d1)

**Comment by mclemente** [comment]
That desync is really weird. I couldn't get to reproduce it.

I need some info:

- How many modules are you using? I've troubleshot issues with desyncs before that were caused by using a lot of modules (100+)
- Can you open your browser's console (F12 -> Console tab), input `game.settings.get("polyglot", "Languages")` and send the object it returns? It'll look like `{aquan: { font: ..., rng, label }, etc`
  - Might be better if you save it as a text file and upload it here

**Comment by Janner3D** [comment]
I am currently running 150 active modules

[Languages.txt](https://github.com/mclemente/fvtt-module-polyglot/files/12672380/Languages.txt)

**Comment by mclemente** [comment]
Can you test this with fewer active modules or even a brand new world? I think it's a desync issue.

Also, try it on Polyglot 2.1.9, it should load faster and might fix this issue.

**Comment by Janner3D** [comment]
I've attempted to activate the 2.1.9 version of this module on a fresh testing world with only it and libWrapper active, and I'm still getting similar issues. Custom languages don't seem to register with different fonts.

**Comment by mclemente** [comment]
Can you try it on 2.1.9.1 now? I finally got to reproduce the issue and I think I found a fix.

**Comment by Janner3D** [comment]
I'm not sure what you did, but that seems to have fixed a lot of my issues! Thank you so much!
One more issue I seem to be having is that it's not registering the default language.
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/35965176/c09eb97e-cb5e-4b47-8eb5-f426b5bca493)
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/35965176/0c2902b9-e738-47c2-9c77-92a268edf505)

Or maybe it is and I'm not sure if displaying the translation for the default language is intentional or not.
Would it be possible to have an option to block the translation for the default language?

**Comment by mclemente** [comment]
You were right, it wasn't working correctly. It should be fine on the latest release.

**Comment by Janner3D** [comment]
That's fixed it!

Thank you for being so dilligent with the fixes. Polyglot now works like a charm for me!
