### ISSUE TITLE
Polygot cant update or install from github, no module.json... check upload/git sync

### ISSUE THREAD

**Issue by galaara98** [mclemente/fvtt-module-polyglot#317]
**Describe the bug**
Polygot cant update or install from github, no module.json... check upload/git sync

Started today

**Comment by galaara98** [comment]
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/178406/c98b4292-2399-455c-8a19-933aadab1594)

**Comment by mclemente** [comment]
Should be fixed now.
