### ISSUE TITLE
Language Settings are not saving for assigned font.

### ISSUE THREAD

**Issue by Zefarch** [mclemente/fvtt-module-polyglot#319]
When you go to language settings and assign a font to a language, it will override your selection with something else random on reload.

1. Go to "Language Settings"
2. Assign a language to a font.
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/99354518/c8776e42-0dd6-414d-9049-e3b67ca07123)
3. Click Save Changes
4. Reload application
5. Go to "Language Settings" 
6. Language settings are now shuffled. 
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/99354518/0b8d89c7-fd8f-40b0-9420-4ef78d6f9af5)

GURPS 4e Game Aid 0.16.6 
Polyglot Version 2.1.11

**Comment by mclemente** [comment]
I created a new world and set the languages just as you did and couldn't replicate this error. Could you try setting a new world up just to be sure?

It might be something else. Someone reported a similar issue (#316), but their issue was fixed on 2.1.10, so I'm not sure what this could be.

**Comment by Zefarch** [comment]
I might have found the source of the issue:
-Regardless of what your language list is, I found that it did not break until I added an Omnispeech language
 -If you add it just under omnispeech, but not your language list, it is fine.
-When you add it both under your language list and ominspeech language, the bug starts happening.
-When I deleted it from the custom language list and kept it on omnispeech, the issue still persisted.
-When I deleted it from both the langauge list and the omnispeech language and reload, it fixes the issue.
-If I add it back to omnispeech language but keep it out of the language list, it does not re-break.

Other strange things I found:
-Changing the default language simply did not apply until several reloads. I had to continually keep changing it and reloading until it finally applied. This might also be related to the omnispeech bug because it didn't seem to happen when I removed it.
-Changing the default language in one world changes the default language in all worlds. It doesn't affect your custom language list, but will scramble everything as there's no longer a default.

**Comment by mclemente** [comment]
I've found other issues with the Omni-languages and fixed them, but I couldn't get that exact behavior while testing, so I'm hoping that was fixed between the fixes on v2.2.

As for the default language setting, I'm not sure about the several reloads, but the value persisting through worlds was a misconfiguration of mine, it should be fixed now.

**Comment by mclemente** [comment]
@Zefarch has this issue been solved?

**Comment by Zefarch** [comment]
No, I'm still having this issue

**Comment by Zefarch** [comment]
After some testing, it seems like omnispeech is not the issue. If I remove the ominispeech language altogether, the problem of language settings swapping randomly between reloads persists. I can't seem to find a setting to prevent that from happening at all, anymore. 

The issue was resolved back in September, but seems to have broken again as of 2.3.20

**Comment by srm-ha** [comment]
This issue also happens with me, using Pathfinder 2e with system languages disabled and about sixteen homebrew languages. It seeeeeems like it might only happen with the last few languages on the list. The first half or so seem mostly stable once I set them (I think).

**Comment by mclemente** [comment]
Update to 2.3.25 and let me know if the issue persists.

**Comment by srm-ha** [comment]
After a quick check it looks like it saves correctly now! Thank you!
