### ISSUE TITLE
Default Language is Not Respected When Custom Languages are Used

### ISSUE THREAD

**Issue by daowrey** [mclemente/fvtt-module-polyglot#320]
**Describe the bug**
When a world is loaded, the language selected by Polyglot is the first language in the list of custom languages rather than the custom language specified in either Default Language entry field.

**To Reproduce**
1. Add "Alpha,Bravo" to Custom Languages.
2. Set Default Language in the Languages tab and the Default Language in the root options menu to "Bravo"
3. Reload world
4. See that "Alpha" is the initial language selected.

**Expected behavior**
"Bravo" would be selected upon loading.

**Screenshots**
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/17040793/6dcfbd94-0c1d-4bf4-b7b9-979e36a4cc95)

 - Pathfinder 2nd Edition [5.6.2]
 - Polyglot Version [2.3]
 - Are you using Babele? No.

**Comment by mclemente** [comment]
Should be fixed now. Thank you for reporting this issue.
