### ISSUE TITLE
Request : Language user list colors of Party members only with PF2e system option

### ISSUE THREAD

**Issue by uniwars** [mclemente/fvtt-module-polyglot#321]
**Is your feature request related to a problem? Please describe.**
Actually the colors balls of Players who can speak a language show all world players and it can be a mess if there is a lot of players (I run a living campaign with 50 players) like this :
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/65986545/9565e87b-319c-4af3-b187-516a97998374)

**Describe the solution you'd like**
Pathfinder 2 has a "Party" system, that let GM add PC to the party to interact with a party sheet. It would be nice is only PC in the party are used to populate the polyglot user list.

**Describe alternatives you've considered**
Another idea would be to only show online players.

**Comment by mclemente** [comment]
Should be fixed now. Let me know if you run into any other issues.
