### ISSUE TITLE
Omnispeech and Omniscient don't work right, at least for GM

### ISSUE THREAD

**Issue by dineshm72** [mclemente/fvtt-module-polyglot#325]
**Describe the bug**
If you give an actor the omnispeech and/or omniscient language, clicking onto that token as GM does not properly translate all languages.  It essentially keeps whatever translations the previous token had.

**To Reproduce**
1. Added an Omnispeech and Omniscient Language to settings:
<img width="451" alt="image" src="https://github.com/mclemente/fvtt-module-polyglot/assets/2231877/af32e09b-48b6-4433-9585-64ebdd1c1521">

2. Added both languages to an actor sheet
<img width="229" alt="image" src="https://github.com/mclemente/fvtt-module-polyglot/assets/2231877/92b7dd56-bfea-4721-a7f1-0637fde2be02">

3. Type a few messages in different languages, some of which no one speaks, some of which only some other tokens speak.

4. As GM, click from token to token and also include selecting no tokens.  All other tokens will work correctly to only show translated speech for languages they know.  When you click on the token that has both the Omnispeech and Omniscient language though, nothing will change when you select that token, it will continue showing whatever the token (or GM view) before it could see.

initial GM view of chat:
<img width="484" alt="image" src="https://github.com/mclemente/fvtt-module-polyglot/assets/2231877/95586cc6-7cea-4027-b36b-ef255ec7fc82">

token selected who speaks Undercommon:
<img width="489" alt="image" src="https://github.com/mclemente/fvtt-module-polyglot/assets/2231877/3654ab4d-33a2-49cc-b810-192e8d9a43e7">

now select omnispeech token, nothing changes:
<img width="491" alt="image" src="https://github.com/mclemente/fvtt-module-polyglot/assets/2231877/c81cf2bd-9254-410c-8de6-be5359516ad3">

now select token who speaks only common, no translations as expected:
<img width="491" alt="image" src="https://github.com/mclemente/fvtt-module-polyglot/assets/2231877/1a8b5d39-2538-44a9-badd-96ced867a7a2">

now select the omnispeech token again, nothing changes, now nothing is translated:
<img width="483" alt="image" src="https://github.com/mclemente/fvtt-module-polyglot/assets/2231877/5cddc79f-a1f8-4aa5-abf7-0f8f28e058dc">

Now select no tokens, GM view, everything translated:
<img width="484" alt="image" src="https://github.com/mclemente/fvtt-module-polyglot/assets/2231877/507963f6-bfb5-44e3-8397-557d8071ab85">

Now select omnispeech token again, nothing changes, everything translated (which happens to be correct in this case):
<img width="490" alt="image" src="https://github.com/mclemente/fvtt-module-polyglot/assets/2231877/ef172ad7-f585-4c61-8c4b-61bd8eeba048">

**Expected behavior**
Omnispeech/omniscient token should translate everything when selected, no matter what tokens were selected immediately beforehand.

**Screenshots**
See above.

 - Game System and version [e.g. dnd5e 1.3.6] foundry 11.309, dnd5e 2.3.1
 - Polyglot Version [e.g. 1.7.3] 2.3.5
 - Are you using Babele? [Yes/No] No

**Additional context**
All testing with just Polyglot, FTC, and some libraries:
<img width="503" alt="image" src="https://github.com/mclemente/fvtt-module-polyglot/assets/2231877/354f2e88-a986-4db1-a95d-4f7bc14e62ac">

**Comment by dineshm72** [comment]
If you turn off both Tongues and Comp Languages languages, the token goes back to working normally (only translating the languages it knows).

**Comment by dineshm72** [comment]
Everything seems to work fine on player clients, even if you give them access to multiple PC actors.  As they switch between them, the proper languages get translated.

**Comment by dineshm72** [comment]
I'll just take this opportunity to ask: what is the practical difference between Omnispeech and Omniscience?  Both seem to translate everything in chat.

Since there is no "spoken" language in a VTT, are they essentially treated the same, gamewise?  (at least in dnd5e?)  And just both offered to allow for more RP reasons?

I'll maybe also point out that there doesn't seem to be any documentation about these features in the wiki.  I had to scrape through the release notes to try to figure them out.

**Comment by mclemente** [comment]
> Since there is no "spoken" language

Spoken = chat messages.
Writte = journal text.

> what is the practical difference between Omnispeech and Omniscience (and Omniglot)? Both seem to translate everything in chat.

**Omniscience (AKA Comprehend Languages):** Characters that know it can read chat messages and journals. They don't get a language to speak or write in.

**Omnispeech (AKA Tongues):** Characters can read chat messages, but can't read journals. They get a language to speak in that is understood by everyone.

**Omniglot:** Characters can speak/write in all other languages. This is effectively a shortcut to avoid checking every checkbox. This one was a requested feature that was introduced after the first two. It doesn't have a "real" use on a D&D game, but might be useful in a game where users get the ability to speak/write everything (I dunno, maybe a sci-fi game where a user gets an universal translator mcguffin?)

>I'll maybe also point out that there doesn't seem to be any documentation about these features in the wiki. I had to scrape through the release notes to try to figure them out.

You just made me realize I haven't updated the Wiki link on the Foundry page. It should have been linking to this https://github.com/mclemente/fvtt-module-polyglot/wiki which explains the journal feature

It doesn't explain the distinction between them, but I always assumed their descriptions were enough to understand their difference. I'll try being more verbose on the descriptions now.

**Comment by mclemente** [comment]
Check version [2.3.6](https://github.com/mclemente/fvtt-module-polyglot/releases/tag/2.3.6) and let me know if the issue persists.

**Comment by dineshm72** [comment]
Yep new version works, thanks!

re: the wiki, I was actually looking at the github page, and didn't see anything about them on that main page.  But I didn't notice the d&d specific page on the sidebar; clicking that now spells everything out, sorry I must have missed it before.

The updated descriptions in the in-game options also help, thanks.

**Comment by dineshm72** [comment]
the d&d wiki also spells out the implications of using the polyglot languages vs. the DAE all languages, which I was going to ask about.  Thanks again for that!

The only little hiccup - I'm not sure what the dots are supposed to convey - which characters understand the language?  Which can speak it?  Which can write it?  If you set these abilities to only speak Tongues or Comp Lang, then that actor doesn't show up as a dot for those languages.  Which (depending on what the dots are supposed to mean) may be misleading.  If you go the DAE approach, they appear as dots on all the languages, which seems like what I as GM at least would want them to mean - these characters understand this language (it's maybe less clear whether it means spoken in chat specifically, or either spoken/written).

**Comment by mclemente** [comment]
That makes sense, I've updated the logic to include characters that know Comprehend Languages and Tongues too.

I've updated the [Home of the wiki](https://github.com/mclemente/fvtt-module-polyglot/wiki) to explain the pips.
