### ISSUE TITLE
Polyglot does not work, "No select2/compat/dropdownCss" error

### ISSUE THREAD

**Issue by m1lklinG** [mclemente/fvtt-module-polyglot#329]
**Describe the bug**
Since one of the least updates polyglot doesn'nt work with GameSystem TheDarkEye anymore. 
You can activate the module. It also does detect the ruleset's languages.. but the dropdown-menu within the chat tab is totally empty.

**Expected behavior**
Before one of those least updates it worked like a charm. GM and Players were able to use it. I expected all GameSystem immanent languages to be shown up in the dropdown menu.

**Screenshots**
<img width="1580" alt="image" src="https://github.com/mclemente/fvtt-module-polyglot/assets/148483620/64815dbc-6128-4d7c-91c6-0989a4c29ab1">

 - Game System and version [e.g. dnd5e 1.3.6]: TDE 5th Edition v5.1.5
 - Polyglot Version [e.g. 1.7.3]: 2.3.8
 - Are you using Babele? [Yes/No]: No

**Comment by mclemente** [comment]
There is a libraby version conflict between them. DSA uses v.4.0.13 while Polyglot uses v4.1.
I've managed to fix this in a hacky way, so I'm keeping this open since there are other systems that use that library that might break things somehow.

**Comment by m1lklinG** [comment]
Thank you very much for your quick response. 
I updated to the recent polyglot version but it actually doesnt work yet. Do i have to apply something myself?

**Comment by mclemente** [comment]
Ok, actually got this fixed now on 2.3.10. Sorry for your troubles.
