### ISSUE TITLE
Queekish language (default settings for wfrp)

### ISSUE THREAD

**Issue by GregorHak** [mclemente/fvtt-module-polyglot#331]
**Is your feature request related to a problem? Please describe.**

I think that Air Ciela for Queekish (default settings for wfrp) is oversight

![obraz](https://github.com/mclemente/fvtt-module-polyglot/assets/99994770/bd932637-da66-4afa-8081-3eb6aee79a19)

**Describe the solution you'd like**
Change Air Ciela to **Skaven** for Queekish default settings for wfrp

**Additional context**
Queekish is a language for wfrp ratmen race

Image from core rulebook for wfrp 4
![obraz](https://github.com/mclemente/fvtt-module-polyglot/assets/99994770/90f2853c-95c4-49b1-ab0a-778afc951f99)

**Comment by mclemente** [comment]
It is, it used to be [Skaven some time](https://github.com/mclemente/fvtt-module-polyglot/blob/1.8.6/module/LanguageProvider.js#L2227C20-L2227C26). There was a lot of copy-pasteing during a refactoring of the code and I missed this language.

Thanks for reporting it.
