### ISSUE TITLE
polyglot 2.3.13 and midi qol 11.1.8 misbehave together

### ISSUE THREAD

**Issue by miromonti** [mclemente/fvtt-module-polyglot#333]
With only these six modules operating...
![Screen Shot 2023-10-29 at 1 41 23 AM](https://github.com/mclemente/fvtt-module-polyglot/assets/38819125/e26a454a-5e5d-4673-9202-cf8959ed9f53)

...This error appears whenever a token is selected:
![Screen Shot 2023-10-29 at 1 09 38 AM](https://github.com/mclemente/fvtt-module-polyglot/assets/38819125/15fb9557-c4ae-4743-ab86-b80243612db7)

Find the Culprit helped determine that Midi QOL and Polyglot are the cause.

Nothing bad happens at first. But eventually, the game lags. Symptoms include players' rolls take a long time to appear, the game seems to freeze, clicking a different token (as a GM) doesn't happen (perhaps taking too long to happen), and browser refresh just doesn't. (Again, perhaps taking too long to happen; I didn't bother to wait further.)

**Expected behavior**
Seamless interaction and no error.

 - Foundry 11.313 and DnD5e 2.3.1
 - Polyglot 2.3.13
 - Are you using Babele? No

**Additional context**
I recognize the issue might be Midi QOL. But as they have 213 issues and Polyglot has 9 (not counting this one), I figure the problem might be realized here sooner.

**Comment by mclemente** [comment]
If you're using Find the Culprit you need to keep disabling modules until it stops throwing errors.

If you disabled Midi Qol it would've stopped throwing errors and it would show this:
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/5288872/6df09255-a026-4589-920a-2e87a156eb47)

This isn't a Polyglot issue. You have messages sent by a deleted user and that's what is breaking Midi.

**Comment by miromonti** [comment]
Thanks for Polyglot. I presented the issue to Midi QOL and added your response.
