### ISSUE TITLE
[Style] Found a better css solution for the element "polyglot-user-list" (very minor issue)

### ISSUE THREAD

**Issue by p4535992** [mclemente/fvtt-module-polyglot#334]
**Is your feature request related to a problem? Please describe.**

With many players on the world there is a "style " issue, the player colors list  is  a little out  ?

![](https://i.imgur.com/IpzuVpw.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mclemente** [comment]
Which system are you on? If dnd5e or pf2e you can create a Group/Party and the characters in it will be the valid ones, so you just swap parties on the setting and it should work.

Also, I'll add a style to make its height limited to the selector's size.

**Comment by p4535992** [comment]
Ty for the clarification
