### ISSUE TITLE
DnD5e 2.4.0 scrambles Common and Missing Language Names in Settings

### ISSUE THREAD

**Issue by schnoodly** [mclemente/fvtt-module-polyglot#337]
**Describe the bug**
On DnD5e 2.4.0, Polyglot now shows Common as scrambled runes. Additionally, the language list in the Settings is now missing the text for the language name.

**To Reproduce**
1. Update DnD5e to 2.4.0
2. Send a message in Common
3. See message with scrambled runes
4. Open Settings
5. Polyglot Language Settings
6. See missing names

**Expected behavior**
Generally, Common should not, and has never been, scrambled.

**Screenshots**
Before (DnD5e 2.3.1)
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/20142693/2bc77a9f-b4be-4aa5-ba92-481221e20ab5)
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/20142693/19401934-7db3-4b81-8d6f-0db9f7e83007)

After 
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/20142693/b3149abd-c73c-4f52-82a8-ad8bcf074691)
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/20142693/dce5a2b0-51aa-498a-a2a1-6ab40a09481c)

 - Game System and version [dnd5e 2.4.0]
 - Polyglot Version [2.3.15]
 - Are you using Babele? [Yes]

**Additional context**
I tried with and without the most recent update of everything, and the issue seems to solely be tied to the new DnD5e update. They seem to have changed how Races work, among other things, though I do not see what could be related to languages.
[Link to changelog](https://github.com/foundryvtt/dnd5e/releases/tag/release-2.4.0)

**Comment by mclemente** [comment]
Fixed on https://github.com/mclemente/fvtt-module-polyglot/commit/ff0dfc446f0dd1646c365ddb7e67ecf4a0bd50e9
