### ISSUE TITLE
I can't add languages in my ACKS game on foundry!

### ISSUE THREAD

**Issue by Fritcher36** [mclemente/fvtt-module-polyglot#340]
**System Name:**
ACKS

**System Repository or Foundry VTT link:**
https://github.com/lastredoubt/foundryacks

**Does the system has the languages set up on Foundry?**
Yes, it does, config.js has the list of languages.

**Does the system uses languages as items?**
I'm not sure, you open Notes tab on the character and add languages with a + button. I suppose it doesn't.
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/40432534/02bc156b-51f3-4712-8fac-8424891662c8)
**Additional context**
I tried using most of the file paths I could imagine in the module settings, but they still didn't register properly so when one of my players opens a dropdown menu in the chat it's either empty or only has Common as a language.

**Comment by mclemente** [comment]
I've managed to add them without any issues. You don't need to add a Data Path, just add the Custom Languages under General Settings -> Languages tab and it should work.

![image](https://github.com/mclemente/fvtt-module-polyglot/assets/5288872/a91d8133-ff02-40e9-b56f-7c5afcdab67e)

**Comment by Fritcher36** [comment]
> I've managed to add them without any issues. You don't need to add a Data Path, just add the Custom Languages under General Settings -> Languages tab and it should work.
> 
> ![image](https://private-user-images.githubusercontent.com/5288872/289779305-a91d8133-ff02-40e9-b56f-7c5afcdab67e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzODk4MDMsIm5iZiI6MTcwMjM4OTUwMywicGF0aCI6Ii81Mjg4ODcyLzI4OTc3OTMwNS1hOTFkODEzMy1mZjAyLTQwZTktYjU2Zi03YzVhZmNkYWI2N2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMTM1ODIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjE1YTQ2ZmVhMWI4YWE5NDM3Y2U3MjdjMDkwNDRiOTc0Zjk0OTg4YWJjZDA4YTEzYzA1NzkxNDdkODgzMjM1MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VmfTYduI2l7jVWgvAtsxAOmkUoNr5nXA5sppxSGxELY)

And you can speak with those languages in chat? My issue was that regardless of how many languages I add to my players' characters, they can't speak them in chat. I wasn't even trying to use custom languages, the default ones in system are enough for me

**Comment by mclemente** [comment]
Have the players actually selected those characters or do they just own them?

Is the actor's prototype token actually linked? Because if you add an unlinked token to the map and them add languages to the actor, the changes won't reflect on the token.

**Comment by mclemente** [comment]
Closing as completed.
No data path needs to be provided. Custom Languages are added as normal. Users with selected actors can read and speak with their known languages.
