### ISSUE TITLE
All languages show as [object Object]

### ISSUE THREAD

**Issue by Zefarch** [mclemente/fvtt-module-polyglot#346]
Instead of showing the font when you use a foreign language, it will just say [object Object]. Text below for native speakers is still translated. 

![image](https://github.com/mclemente/fvtt-module-polyglot/assets/99354518/ed355b2e-18be-457e-90e1-f4dd14f91b8d)

 - Game System and version: GURPS 4e Game Aid 0.16.7
 - Polyglot Version: 2.3.21
 - Are you using Babele?: No

**Comment by demotech89** [comment]
I came here to post this bug as well. It is doing in it in the PF2e system as well. 

GM sees this: 
<img width="210" alt="GM" src="https://github.com/mclemente/fvtt-module-polyglot/assets/147771452/0372d7dd-7885-4311-a6ff-ef774fbb05bf">
 
Players only see this. 
<img width="216" alt="player" src="https://github.com/mclemente/fvtt-module-polyglot/assets/147771452/675e56d4-92f1-4783-b620-332d6c3d3ef7">

**Comment by mclemente** [comment]
Any list of other modules that enhance chat that you're currently running? I'm not getting issues when running without any modules.

**Comment by Zefarch** [comment]
It still presents the same problem with no other modules enabled for me.

**Comment by demotech89** [comment]
Same here, I deactivated every single module except for Polygot, and still says object, Object. Attached is a picture of all modules turned off with what the GM sees and the Player sees in a different browser.

![polygot](https://github.com/mclemente/fvtt-module-polyglot/assets/147771452/1a9181ba-ca24-40ad-8294-b48d16ceb470)

**Comment by mclemente** [comment]
Can you check your Font Settings? There has been an update 15 days ago, but this is the first time I'm hearing about any issues.

Also, which browser are you twow using?

**Comment by demotech89** [comment]
I can check. Anything in particular you would like to know about font settings?

**Comment by demotech89** [comment]
<img width="583" alt="Untitled" src="https://github.com/mclemente/fvtt-module-polyglot/assets/147771452/24a17c92-d4bb-43b5-998b-6b020eda03e1">

Nothing in the settings looks out of place.

**Comment by mclemente** [comment]
> I can check. Anything in particular you would like to know about font settings?

Just opening, checking everything is in order, and then saving them. But that issue should've popped up on the previous version (2.3.20), not the new one.

Maybe check if the issue is present on 2.3.20? The latest changes shouldn't be breaking on any browser.

**Comment by fhavrlent** [comment]
I'm having the same issue since yesterday. All other mods turned off, running Edge 120.0.2210.133.

<img width="293" alt="image" src="https://github.com/mclemente/fvtt-module-polyglot/assets/16169571/81db03e6-849f-4a60-b241-692ca889c658">

**Comment by mclemente** [comment]
Could any of you test if the issue is present on a new world? Might be some misconfiguration from an update, but I'm still clueless since none of the new changes should've affected the output.

**Comment by fhavrlent** [comment]
New world, Pathfinder 2e system

<img width="283" alt="image" src="https://github.com/mclemente/fvtt-module-polyglot/assets/16169571/e7f4af78-76f6-42e8-9b5b-016b3ba0b931">

Same on DnD 5e

<img width="288" alt="image" src="https://github.com/mclemente/fvtt-module-polyglot/assets/16169571/bced47c3-0ccc-4b9a-a724-62b35e7acadf">

**Comment by wealthbeyondmeasure** [comment]
Also having the same issue. The console shows the following issue whenever we try to use a language:

> mmons.js:2070 Error: CreatureSystemData#traits#languages is deprecated. Use CreatureSystemData#details#languages instead.
> 
> Deprecated since Version 5.12.0
> 
> Backwards-compatible support will be removed in Version 6.0.0

   ` at Object.logCompatibilityWarning (commons.js:2059:19)

    at Object.get (pf2e.mjs:1645:84971)

    at pf2eLanguageProvider.getUserLanguages (pf2e.js:227:28)

    at Polyglot.getUserLanguages (logic.js:184:65)

    at Polyglot.updateUserLanguages (logic.js:199:56)

    at Object.controlToken [as fn] (hooks.js:32:17)

    at #call (foundry.js:730:20)

    at Hooks.callAll (foundry.js:687:17)

    at TokenPF2e.control (foundry.js:28654:11)

    at TokenPF2e._onClickLeft (foundry.js:29042:15)

    at TokenPF2e._onClickLeft (foundry.js:56254:11)

    at MouseInteractionManager.callback (foundry.js:31766:17)

    at #handleClickLeft (foundry.js:31954:15)

    at #handleMouseDown (foundry.js:31939:38)

    at Na.notifyListeners (earcut.js:128:75)

    at Na.notifyTarget (earcut.js:128:75)

    at Na.propagate (earcut.js:128:75)

    at Na.dispatchEvent (earcut.js:128:75)

    at Na.mapPointerDown (earcut.js:128:75)

    at Na.mapEvent (earcut.js:128:75)

    at yn.onPointerDown (earcut.js:128:75)
l`

**Comment by RavenknightDM** [comment]
Tested with a new world (Warhammer Fantasy 4e system) and the problem is there with no other mods enabled.

**Comment by mclemente** [comment]
Update to 2.3.22 and let me know if any of you still run into this issue.

**Comment by Aeristoka** [comment]
Looks better here now @mclemente

**Comment by fhavrlent** [comment]
Seems to be working 👍

**Comment by wealthbeyondmeasure** [comment]
> Update to 2.3.22 and let me know if any of you still run into this issue.

Seems sorted now. Thanks for the speedy fix!

**Comment by RavenknightDM** [comment]
Thank you!
