### ISSUE TITLE
Module-registered languages display incorrectly (pf2e)

### ISSUE THREAD

**Issue by JacksonBockus** [mclemente/fvtt-module-polyglot#349]
**Describe the bug**
Module-registered languages are showing up in Polyglot as PF2E.Actor.Creature.Language.mylanguage

**To Reproduce**
Install a module that registers a custom pf2e language in the module.json through the flags; ex
```
"flags": {
    "my-module": {
        "pf2e-homebrew": {
            "languages": {
                "mylanguage": "My Language"
            }
        }
    }
}
```

**Expected behavior**
The language should appear in polyglot as "My Language"

 - Game System and version pf2e 5.12.7
 - Polyglot Version 2.3.26

**Additional context**
If fixing this requires a change to the module registering the language, please let me know what needs to be changed.

**Comment by mclemente** [comment]
I wasn't aware of that structure, sorry. It should be fixed with the latest release.
