### ISSUE TITLE
Polyglot runes not showing in journal text editor

### ISSUE THREAD

**Issue by Janner3D** [mclemente/fvtt-module-polyglot#351]
I'm unable to find the option within the journal text editor to disguise the text as polyglot runes. Am I looking in the wrong place or was this feature removed?

![image](https://github.com/mclemente/fvtt-module-polyglot/assets/35965176/b505c824-2903-4e95-bd4d-a8e931d9f99f)

 - Game System and version [e.g. dnd5e 2.4.1]
 - Polyglot Version [e.g. 2.3.28]
 - Are you using Babele? [No]

**Comment by mclemente** [comment]
Have you changed your Journal editor to TinyMCE?
