### ISSUE TITLE
Option to Limit the Language List to Party's known languages and then "Other"

### ISSUE THREAD

**Issue by MrVauxs** [mclemente/fvtt-module-polyglot#352]
### User Experience

It would be lovely to be able to limit the language list to just the list your players can actually read, and a generic "Other" that you'd then have it expand to either select a specific language from, or be a general "Unknown Language."

![image](https://github.com/mclemente/fvtt-module-polyglot/assets/32039708/9d23421d-d3a7-4330-8a66-672a3058b28a)

### Have you read the Wiki?

- [X] Yes

**Comment by mclemente** [comment]
I've added the Known/Unknown option groups on v2.3.29.

Hiding unknown languages would limit GMs from speaking in those languages at all.
I've also tried setting the Unknown Languages' group to start collapsed, but it was a bit tricky for cases like having an unknown language currently selected, and it had an odd visual bug if the Known group was smaller than the select window's size.

**Comment by MrVauxs** [comment]
This is very good regardless, putting everything known at the top pretty much solves the underlying issue. 

Feel free to close this if you won't work on this further. Thank you!!
