### ISSUE TITLE
Translate for a player-"group" in Dnd5 3.0.2

### ISSUE THREAD

**Issue by MohansWolf** [mclemente/fvtt-module-polyglot#361]
### User Experience

If I use a player-group-actor (don't know i this is only for dnd5 3.02) on a large scale map, like a country, Polyglot does not translate for the individual players of the group. The individual player actors need to be on the map to give them the tyranslation.
Would be nice if it does also work on the group-actor.

### Have you read the Wiki?

- [X] Yes

**Comment by mclemente** [comment]
None of your players have a character assigned to them? https://github.com/mclemente/fvtt-module-polyglot/wiki#actor-selection

**Comment by MohansWolf** [comment]
Players have a character assigned to them, but on this map I use a players group. Rather not have 5 people running around in the city. :-). Polyglot is working if i put the characters themself on the map, but not if i use the player-group icon. As a gamemaster I can see the languages the characters have, even if I use the player-group icon. But the players do not see the translation if I use the group-icon.
By the way. I like Polyglot very much. Thanks.
 
![Schermopname (5)](https://github.com/mclemente/fvtt-module-polyglot/assets/160598961/93e11317-ff3f-482d-a51d-7cf6aad5589b)
![Schermopname (6)](https://github.com/mclemente/fvtt-module-polyglot/assets/160598961/a8880d72-35ff-498f-8e84-ecbe5a7883fd)

**Comment by mclemente** [comment]
Then their Group actor's ownership permission is set to Owner and, as that is the only owned actor they have on the map, they will read and send messages as that actor.
That is how Foundry handles owned tokens on a scene, Polyglot isn't doing anything.

If you want them to be able to read and send messages as their actors and still be able to move the Group's token, add their actors somewhere on the scene and make walls around them so they don't move.
The alternative would be to reduce the ownership permission to at least Observer and move the token yourself.

**Comment by mclemente** [comment]
I have just updated the wiki with a tip on how to handle that behavior.

You could add the players' actors to the map, wall them off with ethereal walls, and then set them as hidden. https://github.com/mclemente/fvtt-module-polyglot/wiki/Understanding-Core-Behavior
