### ISSUE TITLE
Using custom languages instead of pathfinder2e languages

### ISSUE THREAD

**Issue by Jasper-J-R** [mclemente/fvtt-module-polyglot#362]
### User Experience

Hi! I am creating my own setting using the pathfinder 2e rules so I would like to customize my languages while still using the foundry module. I looked over the wiki and I'm not sure I understand how to add custom languages, I'm wondering if perhaps because I'm using the pathfinder 2e system that the option is locked off? Any help would be appreciated, thanks.

### Have you read the Wiki?

- [X] Yes

**Comment by mclemente** [comment]
You have to add languages through PF2e's Homebrew Elements menu.
