### ISSUE TITLE
Custom Languages do not appear in OOC Scramble (New D&D 5E System)

### ISSUE THREAD

**Issue by Zalakoth** [mclemente/fvtt-module-polyglot#364]
### What happened?

Ever since I updated to the new 5E System, I am incapable of using my custom languages in OOC contexts. Mind you, they still function _on a character_ but they do not function when I am trying to post something in that language to my chat. The language simply does not appear.

### Reproduction Steps

<img width="599" alt="Screenshot 2024-03-08 at 7 17 11 PM" src="https://github.com/mclemente/fvtt-module-polyglot/assets/162763383/3b9d57b5-c0c8-4030-9a16-7f53701322a2">
<img width="193" alt="Screenshot 2024-03-08 at 7 18 18 PM" src="https://github.com/mclemente/fvtt-module-polyglot/assets/162763383/dde737db-1d74-44fa-8ecb-13266825cdc1">
<img width="204" alt="Screenshot 2024-03-08 at 7 18 35 PM" src="https://github.com/mclemente/fvtt-module-polyglot/assets/162763383/d11afa85-8fa4-49e8-b96d-10340abbc540">

No matter what I tried, simply adding adding a custom language is enough to recreate this effect (or lack thereof.) As seen in the example here, Akeskian _should_ show up, but it does not. It does show up, but only when a character is under my control (which has not been necessary, historically)

### Which game system, and which version, are you using?

dnd5e 3.0.4

### Which Polyglot version are you using?

2.4.3

**Comment by mclemente** [comment]
Do you have any errors on the console?
I couldn't replicate this. I copied your settings and it just worked. Can you replicate this on a brand new world?

**Comment by Zalakoth** [comment]
I get the following error

Caught (in promise) TypeError: undefined. Cannot create property 'alphabeticOnly' on string '130% Thorass'
[Detected 1 package: polyglot]
    at dnd5eLanguageProvider.loadFonts (Base.js:400:36)
    at setupSteps (Base.js:291:9)
    at async dnd5eLanguageProvider.setup (Base.js:310:4)
    at async Object.fn (polyglot.js:42:2)

The languages do appear when I create a new world. Strange. Still no matter what troubleshooting I do for my pre-existing game, the languages do not show up.

**Comment by mclemente** [comment]
Go into Polyglot's Font Settings and try just saving without changing anything, then reload.

If that doesn't fix it, consider resetting the Font Settings to defaults instead. Be sure to make a backup of its data if you had modified it previously.
Inputting `game.settings.get("polyglot", "Alphabets")` into the console, right-clicking the output and selecting Copy Object, and then pasting it on a notepad would be enough to back it up.

**Comment by Zalakoth** [comment]
Resetting the font settings fixed my problem, thank you!
