### ISSUE TITLE
[Bug] polyglot messes with TinyMCE text editor

### ISSUE THREAD

**Issue by maxobremer** [mclemente/fvtt-module-polyglot#366]
### What happened?

When I have polyglot and lib active then I can't use the TinyMCE text editor to edit my journal entries
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/86924581/9947884e-e46d-448d-b08f-975c65a975f9)

### Reproduction Steps

1. Have an empty world with just polyglot and lib active
2. create a journal entry
3. create a page
4. change the sheet configuration to use TinyMCE

### Which game system, and which version, are you using?

dnd5e 3.0.4

### Which Polyglot version are you using?

1.9.6

**Comment by maxobremer** [comment]
Further context im also using foundry 11 build 315 and libWrapper v1.12.13.0

**Comment by mclemente** [comment]
I can't reproduce this error. What browser are you using?

**Comment by maxobremer** [comment]
Just foundry itself, self hosting and all that

**Comment by maxobremer** [comment]
I'm an idiot and after unlocking the module and updating it all is good. sorry for the bother
