### ISSUE TITLE
Custom Languages not showing in language proficiency

### ISSUE THREAD

**Issue by maxobremer** [mclemente/fvtt-module-polyglot#370]
### What happened?

When adding custom languages they arent available when adding language proficiency

### Reproduction Steps

Open up your fav test world and have only polyglot enabled module wise

1. In polyglot's general settings go to languages
2. Add some custom languages
3. (optional) remove system languages
4. save changes
5. open a character sheet
6. try to add a language and non are added

![image](https://github.com/mclemente/fvtt-module-polyglot/assets/86924581/e256eb88-6412-4be4-bd8c-9c77928f7c4b)

### Which game system, and which version, are you using?

dnd5e 3.1.2

### Which Polyglot version are you using?

2.4.9

**Comment by mclemente** [comment]
I couldn't reproduce the bug. 

![image](https://github.com/mclemente/fvtt-module-polyglot/assets/5288872/9669e39f-da84-4c06-9356-8f0bc231dac4)

**Comment by mclemente** [comment]
Are there any errors on the console?

**Comment by maxobremer** [comment]
Got this error and these warnings
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/86924581/86c761d3-dcdf-48ef-b782-3f00bdcbd6ff)
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/86924581/d43884b4-7ae4-45b5-b342-69a3b640e5d7)

this was in a test world (Test) i have used a couple of times. Just for the double made another test world (Test 2) and there it did work? Im guessing something is leftover or something from old tests in the original test world? Both had only polyglot enabled

**Comment by mclemente** [comment]
Could you input `saveDataToFile(JSON.stringify(game.settings.get("polyglot", "Alphabets"), null, 2), "text/json", "polyglot-alphabets.json")` into the console and upload the file over here?
It will export the module's setting. Last time I've spotted that bug I forgot to ask for the setting so I could try fixing it.

As for the actual fix, follow the instructions here https://github.com/mclemente/fvtt-module-polyglot/issues/364#issuecomment-1986953207

**Comment by maxobremer** [comment]
Currently travelling home but if my Internet provider has fixed shit in their end I will do what you asked in about 2 hours, else I will do it tomorrow when I know stuff will be fixed.

**Comment by maxobremer** [comment]
Here you go, this is from my test world
[polyglot-alphabets.json](https://github.com/mclemente/fvtt-module-polyglot/files/15340273/polyglot-alphabets.json)

**Comment by mclemente** [comment]
> Here you go, this is from my test world [polyglot-alphabets.json](https://github.com/mclemente/fvtt-module-polyglot/files/15340273/polyglot-alphabets.json)
> 

Thank you for providing the old file, that did it for me.

> followed your guide to fix the issue and that worked for both the test and my normal game world. Thanks for the help.

You're welcome. I should've been more careful back when I made changes to the settings. I'm sorry for your troubles.

>Do you need anything from me or is this a one time issue and as such this threat should be closed or not?

It was a one time thing, I'll release an update to make sure nobody else gets affected by this bug.
