### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by emdant** [mclemente/fvtt-module-polyglot#378]
### What happened?

Some systems such as Pathfinder 1e are not yet v12 compatible.

The additional problem here is that the fix for #376 is in 2.4.15, which can't be downloaded because the minimum version of foundry is v12.

### Reproduction Steps

Use Foundry v11, install polyglot and add languages to an actor: errors will show up in the console.

### Which game system, and which version, are you using?

pf1e

### Which Polyglot version are you using?

2.4.10

**Comment by Asothin** [comment]
Manually downloading the module and changing the version to 11 in the module.json, allows it to load. However, none of the messages become scrambled and the "Scramble Out of Character Chat Messages" setting always resets to "None" after saving changes.

Tested with Version:
pf1e: v10.3
Foundry: v11 Build 315
Polyglot: 2.4.15

**Comment by Trellinane** [comment]
Confirmed.  Manually downloaded 2.4.15 and the languages are now present but none of the text is scrambled.  Also when I go to the configure settings for polyglot all of the languages show Object Object in the drop down.  This is a really neat concept and I would like to use it but so far its a bust.

Versions:
pf1e 10.3
Foundry v11.315
polyglot 2.4.15

![image](https://github.com/mclemente/fvtt-module-polyglot/assets/26035193/3cb114a2-0adf-43f2-ae81-b4114812b1c1)

**Comment by Trellinane** [comment]
Nicely done, sir.  Everything seems to be very much in order now.
