### ISSUE TITLE
Missing Module Manifest

### ISSUE THREAD

**Issue by benheise** [mclemente/fvtt-module-polyglot#384]
### What happened?

![Screenshot at 2024-09-04 17-36-44](https://github.com/user-attachments/assets/dab45d9b-60f8-4dc9-93c1-07c9327c8621)

### Reproduction Steps

Install module/Have module installed.
Attempt to update the module.
Sadness. Regret. Shame. Wailing and gnashing of teeth.

### Which game system, and which version, are you using?

pf2e 6.3.1

### Which Polyglot version are you using?

2.4.17

**Comment by BladeFireLight** [comment]
the latest release does not have that file. only the zip

**Comment by mclemente** [comment]
It should be fixed now, thank you for reporting it.
