### ISSUE TITLE
Latest update for WFRP broke Polyglot

### ISSUE THREAD

**Issue by RavenknightDM** [mclemente/fvtt-module-polyglot#388]
### What happened?

Hiya, Polyglot 2.4.19 added Read/Write for the WFRP4e system but something is broken.

### Reproduction Steps

When a character that has knowledge in a language and the Read/Write talent is trying to read a journal document, the text is scrambled. If a character that don't know the language and lacks the Read/Write talent is trying to read a book from the inventory, the text is un-scrambled. (I'm a little uncertain if this is how it is supposed to work.)

Also a character without the Read/Write talent can't speak any other language then the default one in chat. Adding the Read/Write talent to the character re-enables the ability. 

### Which game system, and which version, are you using?

WFRP4e 8.0.2

### Which Polyglot version are you using?

2.4.19

**Comment by patengelbert** [comment]
See https://github.com/mclemente/fvtt-module-polyglot/pull/387#issuecomment-2336819036

**Comment by mclemente** [comment]
Should be fixed with #389, thanks to @patengelbert.
