### ISSUE TITLE
Errors on Pf1e

### ISSUE THREAD

**Issue by hiherp** [mclemente/fvtt-module-polyglot#393]
### What happened?

I am not a dev, and have almost no knowledge for coding stuff. I am also not sure if this would be categorize under bug, but I thank you for your time regardless!

I am getting several errors for all _player characters_. It seems to be something with Polyglot. This is on Pathfinder 1e v10.7 and Foundry 11.315, with no other modules other than Polyglot. I haven't had the chance to test the module more deeply to check if it is working even though it warns errors.

![imagem_2024-09-21_000911771](https://github.com/user-attachments/assets/a86927ed-cb2c-4789-a3fb-205b93cc89b5)

### Reproduction Steps

1. Create an updated pf1e world (currently Pathfinder 1e v10.7, which relies on Foundry 11.315).
2. Active Polyglot module in Manage Modules.
3. Create an actor (can be generic, does not need to name or anything).
3. Create a scene (can also be generic)
4. Press f12 to see DevTools.
5. Drag the actor to the scene canvas.
6. Click/select the actor.

It apparently happens each time the actor is selected. If you f5 and click on the actor, it should list errors again.

### Which game system, and which version, are you using?

Pathfinder 1e v10.7

### Which Polyglot version are you using?

2.4.14

**Comment by mclemente** [comment]
> ### Which Polyglot version are you using?
> 
> 2.4.14

Is this correct? `2.4.14` is V12-only but PF1 is still on V11.
That version was released before PF1 changed how its languages worked. Either downgrade to `2.4.10.2` if you are on V11 or upgrade to the latest version if you are on V12.

**Comment by hiherp** [comment]
That indeed was the issue apparently. Silly me didn't even considered what was likely the most obvious cause. It does not list errors anymore, thanks for your answer!
