### ISSUE TITLE
Dropdown menu without languages

### ISSUE THREAD

**Issue by KnightCebola** [mclemente/fvtt-module-polyglot#394]
### What happened?

Hi, im having an issue where the dropdown menu shows no language options. Im running Foundry v11 build 315, D&D5e v2.4.1, Polyglot v2.4.10. I've tried disabling other chat related modules and UI related modules, but the problem persists. Messing with the polyglot configs also seems to not change anything.

![fvtt polyglot bug](https://github.com/user-attachments/assets/23317ff5-3568-43cf-ae8d-e3338f4da47d)

I have also noticed that in the Language Settings, non appear to exist with the Generic DnD5e provider, im not sure if the base languages are supposed to appear here. 

![no languages polygloy](https://github.com/user-attachments/assets/0c90e214-8d9b-48ee-bf19-e61bc105f58e)

### Reproduction Steps

The bug happens as soon as i run the world, and happens for both the GM and players. 

### Which game system, and which version, are you using?

D&D5e v2.4.1

### Which Polyglot version are you using?

v2.4.10

**Comment by mclemente** [comment]
I think the issue is that you're using an old dnd5e version.
Try updating the system or rolling the module back to v1.9.6 (manifest: `https://github.com/mclemente/fvtt-module-polyglot/releases/download/1.9.6/module.json`) and see if the issue persists.

**Comment by KnightCebola** [comment]
That worked! Thanks a lot!
