### ISSUE TITLE
[Pathfinder 1e] Custom languages are not being loaded

### ISSUE THREAD

**Issue by LeCuay** [mclemente/fvtt-module-polyglot#396]
### What happened?

When loading the total of languages, the custom ones are omitted.

> **Note**: this is most likely because `traits.languages.total` and `traits.languages.customTotal` need to be merged in the loading.

### Reproduction Steps

1) Add a custom language to an NPC.
2) See if the custom language is part of languages selector.

You'll see it isn't displayed.

![imagen](https://github.com/user-attachments/assets/f04513fb-8f21-403f-9889-219efd243c3a)

### Which game system, and which version, are you using?

pf1 10.7

### Which Polyglot version are you using?

2.4.10.2

**Comment by mkahvi** [comment]
This can be seen as an issue in the system itself for not including custom languages in `.total`

**Comment by LeCuay** [comment]
> This can be seen as an issue in the system itself for not including custom languages in `.total`
> 
> Edit: Looking into the code, it seems the customTotal needs to exist separately for some special handling.
> 
> This module should combine the two, the special handling the system needs is irrelevant here.

Seems to be [here](https://github.com/mclemente/fvtt-module-polyglot/blob/master/src/module/providers/pf1.js#L203) already, just not working (?)

**Comment by LeCuay** [comment]
Nevermind it is working, is just not displayed without selecting the character
